# server/swagger.yaml

openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
  description: API Documentation
paths:
  /api/hello:
    get:
      summary: Returns a greeting message
      responses:
        '200':
          description: A greeting message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello World
